/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;




/**
 *
 * @author gonza
 */
public class guia5 extends javax.swing.JFrame {

    /**
     * Creates new form guia5
     */
    public guia5() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jMenu1 = new javax.swing.JMenu();
        Escritorio1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMformularioAlumno = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMmateria = new javax.swing.JMenu();
        JMTFmateria = new javax.swing.JMenuItem();
        JMadministracion = new javax.swing.JMenu();
        JMTmanejoInscripciones = new javax.swing.JMenuItem();
        JMTmanipulacionNotas = new javax.swing.JMenuItem();
        JMconsultas = new javax.swing.JMenu();
        JMTalumnosXmaterias = new javax.swing.JMenuItem();
        JMsalir = new javax.swing.JMenu();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Escritorio1.setPreferredSize(new java.awt.Dimension(1900, 2000));

        javax.swing.GroupLayout Escritorio1Layout = new javax.swing.GroupLayout(Escritorio1);
        Escritorio1.setLayout(Escritorio1Layout);
        Escritorio1Layout.setHorizontalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1900, Short.MAX_VALUE)
        );
        Escritorio1Layout.setVerticalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        getContentPane().add(Escritorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JMformularioAlumno.setText("Alumnos");
        JMformularioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMformularioAlumnoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Formularios de alumnos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMformularioAlumno.add(jMenuItem1);

        jMenuBar1.add(JMformularioAlumno);

        JMmateria.setText("Materia");

        JMTFmateria.setText("Formulario de Materia");
        JMTFmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMTFmateriaActionPerformed(evt);
            }
        });
        JMmateria.add(JMTFmateria);

        jMenuBar1.add(JMmateria);

        JMadministracion.setText("Administracion");
        JMadministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMadministracionActionPerformed(evt);
            }
        });

        JMTmanejoInscripciones.setText("Manejo de inscripciones");
        JMTmanejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMTmanejoInscripcionesActionPerformed(evt);
            }
        });
        JMadministracion.add(JMTmanejoInscripciones);

        JMTmanipulacionNotas.setText("Manipulacion de Notas");
        JMTmanipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMTmanipulacionNotasActionPerformed(evt);
            }
        });
        JMadministracion.add(JMTmanipulacionNotas);

        jMenuBar1.add(JMadministracion);

        JMconsultas.setText("Consultas");
        JMconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMconsultasActionPerformed(evt);
            }
        });

        JMTalumnosXmaterias.setText("Alumnos por Materias");
        JMTalumnosXmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMTalumnosXmateriasActionPerformed(evt);
            }
        });
        JMconsultas.add(JMTalumnosXmaterias);

        jMenuBar1.add(JMconsultas);

        JMsalir.setText("Salir");
        JMsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMsalirMouseClicked(evt);
            }
        });
        JMsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMsalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(JMsalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMTmanipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMTmanipulacionNotasActionPerformed
        Escritorio1.removeAll();
        Escritorio1.repaint();
        CargadeNotas notas= new CargadeNotas();
        notas.setVisible(true);
        Escritorio1.add(notas);
        Escritorio1.moveToFront(notas);

        // TODO add your handling code here:

    }//GEN-LAST:event_JMTmanipulacionNotasActionPerformed

    private void JMformularioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMformularioAlumnoActionPerformed
              // TODO add your handling code here:
       
    }//GEN-LAST:event_JMformularioAlumnoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Escritorio1.removeAll();
        Escritorio1.repaint();
        FormularioAlumno alu= new FormularioAlumno();
        alu.setVisible(true);
        Escritorio1.add(alu);
        Escritorio1.moveToFront(alu);        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMTFmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMTFmateriaActionPerformed
        Escritorio1.removeAll();
        Escritorio1.repaint();
        GestiondeMateria materia = new GestiondeMateria();
        materia.setVisible(true);
        Escritorio1.add(materia);
        Escritorio1.moveToFront(materia);         // TODO add your handling code here:
    }//GEN-LAST:event_JMTFmateriaActionPerformed

    private void JMadministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMadministracionActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_JMadministracionActionPerformed

    private void JMTalumnosXmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMTalumnosXmateriasActionPerformed
       Escritorio1.removeAll();
        Escritorio1.repaint();
        ConsultaAlumnos calu= new ConsultaAlumnos();
        calu.setVisible(true);
        Escritorio1.add(calu);
        Escritorio1.moveToFront(calu);
        // TODO add your handling code here:
    }//GEN-LAST:event_JMTalumnosXmateriasActionPerformed

    private void JMTmanejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMTmanejoInscripcionesActionPerformed
        Escritorio1.removeAll();
        Escritorio1.repaint();
        FormularioInscripcion inscrip = new FormularioInscripcion();
        inscrip.setVisible(true);
        Escritorio1.add(inscrip);
        Escritorio1.moveToFront(inscrip);  // TODO add your handling code here:
    }//GEN-LAST:event_JMTmanejoInscripcionesActionPerformed

    private void JMconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMconsultasActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_JMconsultasActionPerformed

    private void JMsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMsalirActionPerformed
        
    }//GEN-LAST:event_JMsalirActionPerformed

    private void JMsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMsalirMouseClicked
    System.exit(0);
    }//GEN-LAST:event_JMsalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guia5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guia5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guia5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guia5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new guia5().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio1;
    private javax.swing.JMenuItem JMTFmateria;
    private javax.swing.JMenuItem JMTalumnosXmaterias;
    private javax.swing.JMenuItem JMTmanejoInscripciones;
    private javax.swing.JMenuItem JMTmanipulacionNotas;
    private javax.swing.JMenu JMadministracion;
    private javax.swing.JMenu JMconsultas;
    private javax.swing.JMenu JMformularioAlumno;
    private javax.swing.JMenu JMmateria;
    private javax.swing.JMenu JMsalir;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
